[package]
name = "chat"
version = "0.1.0"
authors = ["bofeiw <bofei@mail.com>"]
edition = "2018"

[profile.release]
lto = true

[lib]
crate-type = ["cdylib"]

[dependencies]
smart-contract = "0.2.0"
smart-contract-macros = "0.2.0"
